### ISSUE TITLE
Credo che sia cambiato

### ISSUE THREAD

**Issue by compasoft** [Leone25/reader-plus-downloader#1]
Ciao Enrico,
Ho fatto tutto il procedimento solo che premendo f12 e filtrando le richieste non c'è nè il link nè il json

A me compare questo:
https://**************.cloudfront.net/resources/products/epubs/generated/********-****-****-****-************/OEBPS/page000.xhtml

invece di questo:
https://**************.cloudfront.net/resources/products/epubs/generated/********-****-****-****-************/foxit-assets/pages/page

cosa posso fare?

**Comment by Leone25** [comment]
il fatto che sia cambiato il link non è un problema, semplicemente inserisci quello al posto del vecchio

per quanto riguarda il json, prova a ricaricare la pagina con il pannello già aperto, di solito ricompare. Alla peggio scorri allultima pagina e guarda il numero più alto che ti compare nelle richieste

**Comment by compasoft** [comment]
ho fatto quello che mi hai detto ma mi da un errore del tipo che non è un png file

**Comment by Leone25** [comment]
hmmm interessante, sarà un altro formato, dovrò fare dei controlli

hai provato a sostituire la parte finale dellurl con quello che dovrebbe essere e vedere se va?

**Comment by compasoft** [comment]
si ho provato, non funziona
continua a dirmi l'input non è un file png.

**Comment by compasoft** [comment]
Si può fare così per fare delle prove
 I libri delle medie della pearson se inserisci il codice ISBN in attiva prodotto te lo attiva gratis, senza spendere un centesimo.
Purtroppo solo quelli

**Comment by compasoft** [comment]
ok ho scoperto questo:
ci sono libri diversi anche se si appoggiano a reader +

Per esempio:
Bravi in scienze (un libro delle medie) ha come link questo:
https://.cloudfront.net/resources/products/epubs/generated/----**/foxit-assets/pages/page 
ed è compatibile con lo script
Mentre un secondo libro (Occhi sul mondo) ha questo:
https://.cloudfront.net/resources/products/epubs/generated/----**/OEBPS/page000.xhtml
e non è compatibile con lo script

**Comment by Leone25** [comment]
mi sapresti dire l'ibsn di un libro attivabile gratuitamente che presenta il problema?

**Comment by compasoft** [comment]
ISBN : 9788869105128 (Libro che **non** presenta il problema)
ISBN: 9788839537737 (Libro che **presenta** il problema)

**Comment by compasoft** [comment]
sono entrambi attivabili gratuitamente andando su attiva prodotto e inserendo il codice così come ti ho scritto

**Comment by Leone25** [comment]
ok ho trovato!

per scaricare queli libri vai nello script.js ed edita linea 24 cambiando quel `embedPng` con un `embedJpg` e sostituisci linea 22 con questo:
```js
let pageData = await fetch(baseUrl+('000'+(i+1)).slice(-3)+".jpg").then((res) => res.arrayBuffer());
```

adesso esegui lo script 

quando ti chiede il link dagli il link strano, rimuovendo il `page000.xhtml` e aggiungendo `images/bg`

quando ti chiede il token inserisci qualunque cosa tu voglia, non serve (non so perchè ma lo chiedo anche se non lo uso mai 😂 )

quando ti chiede la pagina semplicemente scorri all'ultima pagina nel reader ed inserisci il numero più alto che vedi nella lista delle richieste

un po' macchinoso, ma dovrebbe andare

**Comment by compasoft** [comment]
Ok, grazie mille
provo e ti faccio sapere

**Comment by compasoft** [comment]
non funziona, mi da tipo questo errore:
```
Downloading page 1/288
(node:576) UnhandledPromiseRejectionWarning: Error: SOI not found in JPEG
    at Function.<anonymous> (C:\Users\Admin\Desktop\reader-plus-downloader-main\node_modules\pdf-lib\cjs\core\embedders\JpegEmbedder.js:43:27)
    at step (C:\Users\Admin\Desktop\reader-plus-downloader-main\node_modules\tslib\tslib.js:141:27)
    at Object.next (C:\Users\Admin\Desktop\reader-plus-downloader-main\node_modules\tslib\tslib.js:122:57)    at C:\Users\Admin\Desktop\reader-plus-downloader-main\node_modules\tslib\tslib.js:115:75
    at new Promise (<anonymous>)
    at Object.__awaiter (C:\Users\Admin\Desktop\reader-plus-downloader-main\node_modules\tslib\tslib.js:111:16)
    at Function.JpegEmbedder.for (C:\Users\Admin\Desktop\reader-plus-downloader-main\node_modules\pdf-lib\cjs\core\embedders\JpegEmbedder.js:37:24)
    at PDFDocument.<anonymous> (C:\Users\Admin\Desktop\reader-plus-downloader-main\node_modules\pdf-lib\cjs\api\PDFDocument.js:905:69)
    at step (C:\Users\Admin\Desktop\reader-plus-downloader-main\node_modules\tslib\tslib.js:141:27)
    at Object.next (C:\Users\Admin\Desktop\reader-plus-downloader-main\node_modules\tslib\tslib.js:122:57)(Use `node --trace-warnings ...` to show where the warning was created)
(node:576) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:576) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by Leone25** [comment]
nani

**Comment by Leone25** [comment]
prova a rimettere linea 24 com'era. . . potrebbe essere un png anche se dice altro

**Comment by compasoft** [comment]
sono riuscito a scaricare il file di questo ebook, sembra un epub scompattato
come te lo posso passare?

**Comment by compasoft** [comment]
dentro al file ci sono jpg ma sono solo gli sfondi, le parole vengono messe dai file xhtml

**Comment by Leone25** [comment]
sono 99% sicuro che gli epub sono semplicissimi zip quindi tecnicamente puoi zippare tutto e cambiare l'estensione e dovrebbe aprirti come epub

poi ci sono vari convertitori online per convertire in pdf

**Comment by compasoft** [comment]
[60e3ffaf98588e4ff609798d.zip](https://github.com/Leone25/reader-plus-downloader/files/7330904/60e3ffaf98588e4ff609798d.zip)
non riesco a convertirli mi da sempre errore, anche se si aprono 
guarda

**Comment by compasoft** [comment]
[prova3.pdf](https://github.com/Leone25/reader-plus-downloader/files/7330926/prova3.pdf)
ecco smanettando ho cambiato una riga ed è uscito questo, ma sono solo degli sfondi

**Comment by Leone25** [comment]
interessante,

sinceramente non so come altro aiutarti, mi dispiace

**Comment by compasoft** [comment]
vabbè tranquillo

**Comment by compasoft** [comment]
ah comunque lo sai che in questo periodo con il tuo script pdf bsmart puoi avere tutti i libri che vuoi.
basta cambiare la classe ogni volta che vuoi scaricare un libro diverso.
Vale solo fino alla fine di questo mese

**Comment by Leone25** [comment]
Ah ok
