### ISSUE TITLE
problemi con nome utente e password

### ISSUE THREAD

**Issue by LEO-CAF** [Leone25/reader-plus-downloader#10]
ciao, sono sicuro al cento per cento di aver messo nome utente (ho provato sia con nome utente che con la mail) e password giusti, ma continua a dirmi login failed, consigli? le librerie le ho installate

p.s. ti ho scoperto da un video di uno youtuber poco famoso (marco agnese), l'hai visto il video? è uscito da pochi giorni

**Comment by Leone25** [comment]
Mi fa piacere sapere che i miei script vengano condivisi anche su youtube.

Parlando del tuo problema non saprei come aiutarti, è decisamente strano, prova a sostituire riga 30 con 
```js
let email = 'email o username';
let password = 'password';
```
Ovviamente propriamente completati (le vergoletge devono rimanete però).

Fammi sapere

**Comment by LYZERPI** [comment]
anche io ho lo stesso problema. da browser ho controllato la password e l'username e niente. la riga 30 di quale file?

**Comment by Leone25** [comment]
`index.js`

**Comment by Leone25** [comment]
purtroppo ho brutte notizie, cioè per me funziona perfettamente, quindi è probabile che stiate facendo un errore voi o magari c'è qualcosa che non va nel vostro pc, non so

**Comment by LYZERPI** [comment]
<img width="403" alt="PearsonPNG" src="https://user-images.githubusercontent.com/79585503/201732766-7bdbecaa-63fc-4713-9302-1178b9125eef.PNG">


Il cambio finale dovrebbe essere questo? perchè se incollo tutto sulla riga 30 dopo dovrei cancellare una parentesi che si apre
<img width="339" alt="ipotesi" src="https://user-images.githubusercontent.com/79585503/201732629-f26f1085-8b58-48d4-9c34-aad2109d6201.PNG">

**Comment by Leone25** [comment]
Scusa ho sbagliato io, intendevo di sostituire riga 28

**Comment by LEO-CAF** [comment]
ho provato a sostituire riga 28 ma mi dà errore: 
`SyntaxError: Identifier 'email' has already been declared`

posso mettere la mail e la password direttamente nel file? se si a che riga?

cmq tutte le altre repository funzionano perfettamente, solo questa mi dà questo problema

**Comment by Leone25** [comment]
devi sostituire riga 28 col testo che ti ho mandato prima e devi scrivere dentro le virgolette le tue credenziali

**Comment by LEO-CAF** [comment]
scusami tanto, avevo letto male il tuo primo messaggio, cmq mi dà questo errore:
`let {email, password} = await prompt.get(schema); SyntaxError: Identifier 'email' has already been declared`

**Comment by Leone25** [comment]
Devi rimuovere quello che c'era su riga 28

**Comment by Leone25** [comment]
Ok allora ho capito cosa c'è che non va . . .
Pearson ha fatto un aggiornamento al sito, e adesso è richiesto un captcha (non visibile sul sito) per accedere, purtroppo è impossibile emulare un captcha, quindi credo che eventualmente metterò come archivio questa repo e farò un'estensione per browser per scaricare i libri direttamente da li, ma per adesso mi dispiace ma non c'è modo di bypassare questa sicurezza

**Comment by LEO-CAF** [comment]
ok, grazie dell'aiuto
