### ISSUE TITLE
Libro da 1KB

### ISSUE THREAD

**Issue by davimeglioli** [Leone25/reader-plus-downloader#12]
Ho scaricato un libro e funziona perfettamente, cercando di scaricarne un altro, me lo scarica istantaneamente, crreando un pdf da 1kb con il nome del libro, che però è illeggibile
[Svolte 2.pdf](https://github.com/Leone25/reader-plus-downloader/files/10050610/Svolte.2.pdf)

**Comment by Leone25** [comment]
Ci sono dei problemi con dei recenti aggiornamenti al sito della pearson che non possono essere bypassati con le tecniche attuali, verranno risolte eventualmente, ma per adesso non si può fare niente
