### ISSUE TITLE
Downloading Error

### ISSUE THREAD

**Issue by luciancj** [Leone25/reader-plus-downloader#2]
Downloading pages
Downloading page 1/643
node:internal/process/promises:279
            triggerUncaughtException(err, true /* fromPromise */);
            ^

[UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "The input is not a PNG file!".] {
  code: 'ERR_UNHANDLED_REJECTION'
}

Node.js v17.9.0

**Comment by Leone25** [comment]
hello,

likely you inputted the wrong data, unless something changed on their end. If you want more advance support please contact me trough twitter (same name + 03)
