### ISSUE TITLE
Not working anymore

### ISSUE THREAD

**Issue by arminanton** [Leone25/reader-plus-downloader#5]
I'm not getting past the login part, it returns no json on that post method.

**Comment by Leone25** [comment]
Very weird, it works for me tho :L 
Have you checked you credentials?

**Comment by Excelerator-byte** [comment]
I'm getting the same issue and it says "Error: Login failed". I tried this multiple times and its not the credentials.

**Comment by arminanton** [comment]
This one worked fine for me:
https://github.com/lucafont2/pearson-downloader
I have run that on gitpod.

**Comment by Leone25** [comment]
be aware that this is built on the italian website so perhaps there are some differences and issues with users of sites of other regions

**Comment by ghost** [comment]
Hello.
After following the procedure and downloading the book, I get the pdf, but if I try to open it, I get a message saying the file is corrupt or damaged.
I have tried different PDF readers and re-running the procedure, do you have any advice on how I can fix it?
Thanks in advance!

**Comment by arminanton** [comment]
Maybe the Italian server from Pearson is not retrieving the unencrypted version of the desired file. Try following the repo steps that I posted in my previous comment. That one allowed me to download all books I ever had assigned to my account (even those I don't have a subscription to anymore, but that I had in the past).

**Comment by ghost** [comment]
Thank you for your response.
I just tried, but it only finds me old Pearson books; it doesn't find me 'reader+' books.

**Comment by arminanton** [comment]
instead of downloading all of them, you can modify the line https://github.com/lucafont2/pearson-downloader/blob/master/main.js#L27 to do a console.log of the titles, then once you find your title there, you should be able to add an if() there to select only that title for download (as the current script would download everything it could find there).

**Comment by Leone25** [comment]
In the readme there is a description of what it's happening

Unfortunately pearson uses 1000+1 different formats to delive their books and I haven't found the time yet to write the conversion software for the weird epub format that is giving you problems rn
