### ISSUE TITLE
DiBook downloader request

### ISSUE THREAD

**Issue by dmnfe** [Leone25/reader-plus-downloader#6]
That's not an issue but it was the only way I had to contact you; I wanted to ask you if you could make a DiBook downloader, maybe using the cookies or the jwt token that the page provides, since the reader takes the books from a crypted pdf and I think it uses the token to unlock it (idk how). It would be amazing if you could help me,
thanks anticipately<3

**Comment by Leone25** [comment]
Hello,

I never had a book on that platform but I'd be happy to help on my free time, feel free to dm me on twitter same name + 03
