### ISSUE TITLE
Strange pdf format.

### ISSUE THREAD

**Issue by lui75** [Leone25/reader-plus-downloader#7]
I followed your advice, changed the extension from .pdf to .zip, extracted the archive with Keka (I am on macOS) and yes, I can browse the book as an xhtml file (there is an nav (index) xhtml file) using firefox. All the pages are xhtml file. Is it possible to convert them all into pdf and then merge them (they are images with links to media file or resources on line)? That would be awesome! Thanks for your work!

**Comment by Leone25** [comment]
Unfortunately, it's not straightforward.
Even though it's supposed to be an epub compatible book, it really isn't, I've tried multiple converters, and none gave usable results.
The main issue is that the images are only for background most of the time, and the actual text content is in the html (this allows it to still be selectable and stuff). As stated, I wish in the future to write a proper converter but it's definitely not something happening right now, but I'm always open if someone wishes to contribute.
