### ISSUE TITLE
Collaborazione??

### ISSUE THREAD

**Issue by FelixFrog** [Leone25/reader-plus-downloader#8]
Ciao! Ho visto il tuo lavoro e vorrei condividere le mie conoscenze con te e magari creare qualcosa di buono per altri. Ho una mia suite di script per scaricare pdf da varie fonti, magari vuoi darci un occhiata? Sa mi vuoi contattare la mia mail è (redacted)

**Comment by Leone25** [comment]
dipende un po' da cosa ti hai in mente ... se sono script per altre piattaforme puoi pubblicarli te sulla tua pagina  di github

**Comment by FelixFrog** [comment]
Siccome non è il massimo pubblicare certi "algoritmi" al pubblico come script contenenti chiavi e url in chiaro (dato che poi i vendor sono liberi di cambiare tutto quello che vogliono una volta che scoprono come i loro contenuti sono stati caricati) sarebbe meglio trovare un altro modo, che sia più facile e conveniente ma che dia via meno dettagli (per esempio un sito web)

**Comment by Leone25** [comment]
Nah, intanto fanno ben poco per bloccarli, non che possano.

Il massimo delle modifiche effettuate sono state cambiare un paio di url e modificare le procedure di login, ma per esempio, recriptare i file richiederebbe troppa potenza di calcolo per essere una tattica pratica. E tra l'altro considerando che le chiavi erano in chiaro, pubbliche e facili da reperire, tenerle segrete non è chiaramente loro interesse.

Nell'anno e mezzo che questi script sono esistiti, l'unico contatto da parte delle case editrici è stata una minaccia di morte da parte di uno sviluppatore della Zanichelli in forma non ufficiale. Per tanto, penso che al contrario la cosa corretta sia renderli pubblici senza limitazioni, poi ovviamente io non ti obbligo a fare niente, devi decidere te che cosa farne del frutto del tuo tempo.

Vorrei concludere aggiungendo un'informazione sulla questione del sito web: fornendo uno script che ogni singolo utente esegue sul proprio dispositivo, fornendo le proprie informazioni che vengono inviate esclusivamente alla casa editrice per le operazioni necessarie per ottenere il libro, rimuove in buona parte se non per tutto la responsabilità per la creazione di una copia di materiale posto sotto copyright dallo sviluppatore dello script; in questa situazione lo script si limita a salvare il libro sulla macchina dell'utente senza passare da terzi; fornendo un sito web (che usufruisce di un backend che si occupa delle operazioni di estrazione e condivisione del libro) pone colui o coloro che offrono il servizio non solo a rischi di tipo informatici (es. attacchi informatici) ma anche a rischi di tipo legale dato che la permanenza, anche temporanea, di contenuti posti sotto copyright su dispositivi che non sono di proprietà dell'utente (il lettore che vuole scaricare la copia del proprio libro, e che dispone di una copia digitale autorizzata) causa un illecito, fornendo una scusa facile per fare reclamo alla polizia postale e perseguire legalmente il creatore/i. Ovviamente come prima, se vuoi prenderti il rischio non sarò io a fermarti.

Spero di averti illuminato sulle mie motivazioni e di averti guidato correttamente nelle tue future decisioni.

**Comment by FelixFrog** [comment]
Ok grazie dell'opinione. Ho deciso di rendere pubblico il mio progetto ([qui](https://github.com/FelixFrog/pdfgrabber)).
