### ISSUE TITLE
invalid PDF

### ISSUE THREAD

**Issue by MarkupMark** [Leone25/reader-plus-downloader#9]
When generating the file is small (always 397-398 bytes) and even the old books that worked a while ago now stopped working, is there any way to fix it? 

thank you and have a nice day

**Comment by Leone25** [comment]
could you please open the generated document in https://hexed.it and show me the beginning?

**Comment by DamianoMagrini** [comment]
Hi Enrico! If @Marcosouls7 is having the same problem as me, the file contains the following 397-byte "access denied" HTML page:

```html
<HTML><HEAD>
<TITLE>Access Denied</TITLE>
</HEAD><BODY>
<H1>Access Denied</H1>
 
You don't have permission to access "http&#58;&#47;&#47;etext&#46;pearson&#46;com&#47;eps&#47;pearson&#45;reader&#47;dc56700d&#45;a810&#45;47e1&#45;b625&#45;c119a18ef81f&#47;etext1updfs&#47;CM91287138&#95;uPDF&#46;pdf" on this server.<P>
Reference&#32;&#35;18&#46;44657b5c&#46;1667923889&#46;f32c1e0
</BODY>
</HTML>
```

It only appears to happen with books that were activated today, or very recently — I am trying to download books I activated a while ago and they are working properly.

Thank you for your assistance and your awesome projects! They are really useful to very many people.

**Comment by Leone25** [comment]
That was my suspicion, marco probably just put some wrong info that that's why it's giving issue, unfortunately compiters are precise and don't allow mistakes lol

**Comment by DamianoMagrini** [comment]
Thanks for getting back to us. Pearson's servers seem to be acting up right now (I'm now getting a gateway time-out), so it may be better to wait until their issues are resolved before investigating this one. I'll let you know if it persists!

**Comment by Leone25** [comment]
Would be surprised if they actually try to so something to actively stop this script from working

**Comment by DamianoMagrini** [comment]
Aha, got it. They just updated the auth logic, so the request to `https://etext.pearson.com/api/nextext-api/v1/api/nextext/eps/authtoken` ([here](https://github.com/Leone25/reader-plus-downloader/blob/main/index.js#L197)) returns:

```js
{
  timestamp: '2022-11-09T14:05:28.536+00:00',
  status: 404,
  error: 'Not Found',
  path: '/nextext-api/v1/api/nextext/eps/authtoken'
}
```

And this breaks the script if `booklist[bookId].type == 'etext'`. I found a solution, I'll submit a PR in a minute.

**Comment by Leone25** [comment]
I appreciate the help and the laugh

**Comment by MarkupMark** [comment]
Hi, first of all thanks for what you are doing,
I tried the updated code on Mac and even on Windows but It doesn't seem to work: I can login with my account and I see my books, but after i chose the book to download the program says "Downloading..." and never gives an answer, have they fixed the script?

**Comment by Leone25** [comment]
how much have you waited? because it can take very long, the files aren't the smallest

**Comment by MarkupMark** [comment]
I waited more than 10 minutes without response, but before it actually downloaded everyone of my books in under 1, even heavy ones

**Comment by Leone25** [comment]
Ye something is definitely wrong but i need to talk to you more privately to be able to help you, wpuld ypu mind contacting me on twitter (same name + 03)?
